#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
STAGE 2: Compute mesh with viscous layers using SALOME Netgen.
Exports OpenFOAM case (polyMesh) with boundary layers.
Adds refineBox volumetric refinement in SALOME using Netgen local size.
Adds tip-wake line refinement from tip CSV if found.
No snappyHexMesh -- viscous layers handled entirely in SALOME.

Sizing logic (unified with snappyMesh):
  max_size = max(cube_dx, cube_dy, cube_dz) / 50.0
  surf_size = xl * 0.01
  min_size = surf_size / 2
  refine_local_size = max_size / 4
  tip_wake_refine_size = surf_size * 2

checkMesh-compatible output (ALL files auto-generated by exportToFoam):
  - constant/polyMesh: points, faces, owner, neighbour, boundary, cellZones
  - 0/p: volScalarField, fixedValue uniform 0
  - 0/U: volVectorField, fixedValue uniform (0 0 0)
  - system/controlDict: application=checkMesh, writeFrequency=0
  - system/fvSchemes: default schemes for simpleFoam
  - system/fvSolution: SIMPLE solver settings

Final script (confirmed 2026-07-22):
  Stage 1: calculate_mesh_params.py
  Stage 2: compute_mesh.py
  No templates needed -- exportToFoam generates complete case.
"""

import sys
import os
import json
import math
import time
import csv
import salome
import GEOM
import SMESH
from salome.geom import geomBuilder
from salome.smesh import smeshBuilder

# Write to both console and log file
class TeeOutput:
    def __init__(self, log_path):
        self.log_file = open(log_path, 'w')
        self.log_name = os.path.basename(log_path)
    def write(self, data):
        try:
            sys.__stdout__.write(data)
        except:
            pass
        try:
            self.log_file.write(data)
            self.log_file.flush()
        except:
            pass
    def flush(self):
        try:
            self.log_file.flush()
        except:
            pass

_script_name = os.path.splitext(os.path.basename(sys.argv[0]))[0]
_log_file = os.path.join(os.path.dirname(os.path.abspath(sys.argv[0])), f"{_script_name}.log")
sys.stdout = TeeOutput(_log_file)

# Initialize
salome.salome_init()
geompy = geomBuilder.New()
smesh = smeshBuilder.New()

def format_table(headers, rows):
    """Format data as ASCII table"""
    col_widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            col_widths[i] = max(col_widths[i], len(str(cell)))
    lines = []
    separator = "+" + "+".join("-" * (w + 2) for w in col_widths) + "+"
    header_line = "|" + "|".join(f" {h:^{col_widths[i]}} " for i, h in enumerate(headers)) + "|"
    lines.append(separator)
    lines.append(header_line)
    lines.append(separator)
    for row in rows:
        row_line = "|" + "|".join(f" {str(cell):<{col_widths[i]}} " for i, cell in enumerate(row)) + "|"
        lines.append(row_line)
    lines.append(separator)
    return "\n".join(lines)


# == MeshBuffer helper for OpenFOAM export ==
class MeshBuffer(object):
    def __init__(self, mesh, v):
        i = 0
        faces, keys = list(), list()
        fnodes = mesh.GetElemFaceNodes(v, i)
        while fnodes:
            faces.append(fnodes)
            keys.append(tuple(sorted(fnodes)))
            i += 1
            fnodes = mesh.GetElemFaceNodes(v, i)
        self.v, self.faces, self.keys, self.fL = v, faces, keys, i
    @staticmethod
    def Key(fnodes): return tuple(sorted(fnodes))


def write_patch_field(dirname, fname, field_type, patch_names, patch_nfaces, internal_value=0):
    """Write 0/p or 0/U field file with correct patch face counts."""
    path = os.path.join(dirname, fname)
    with open(path, 'w') as f:
        f.write("FoamFile\n{\n")
        f.write("    version     2.0;\n")
        f.write("    format      ascii;\n")
        f.write("    class       %s;\n" % field_type)
        f.write('    location    "0";\n')
        f.write('    object      %s;\n' % fname)
        f.write("}\n\n")
        f.write("internalField uniform %s;\n\n" % str(internal_value))
        f.write("boundaryField\n\n(\n")
        for i, pname in enumerate(patch_names):
            nf = patch_nfaces[i]
            f.write("    %s\n" % pname)
            f.write("    {\n")
            f.write("        type            fixedValue;\n")
            if field_type == "volScalarField":
                f.write("        value           uniform %s;\n" % str(internal_value))
            else:
                f.write("        value           uniform (0 0 0);\n")
            f.write("    }\n\n")
        f.write(")\n")


def exportToFoam(mesh, dirname, base_name):
    """Export SALOME mesh to complete OpenFOAM case structure."""
    if not os.path.exists(dirname): os.makedirs(dirname)
    volumes = mesh.GetElementsByType(SMESH.VOLUME)
    smesh_int = smeshBuilder.New()
    filter_free = smesh_int.GetFilter(SMESH.EDGE, SMESH.FT_FreeFaces)
    extFaces = set(mesh.GetIdsFromFilter(filter_free))
    buffers = [MeshBuffer(mesh, v) for v in volumes]
    nrExtFaces = len(extFaces)
    nrFaces = int((sum(b.fL for b in buffers) + nrExtFaces) / 2)
    nrIntFaces = nrFaces - nrExtFaces

    faces, facesSorted = [], {}
    bcFaces, bcFacesSorted = [], {}
    grpStartFace, grpNrFaces, grpNames = [], [], []
    volumeGroups = []
    ofbcfid = 0

    for gr in mesh.GetGroups():
        g_type = gr.GetType()
        if g_type == SMESH.FACE:
            grpNames.append(gr.GetName())
            grIds = gr.GetIDs()
            grpStartFace.append(nrIntFaces + ofbcfid)
            grpNrFaces.append(len(grIds))
            for sfid in grIds:
                fnodes = mesh.GetElemNodes(sfid)
                key = MeshBuffer.Key(fnodes)
                bcFaces.append(fnodes)
                bcFacesSorted[key] = ofbcfid
                ofbcfid += 1
        elif g_type == SMESH.VOLUME:
            volumeGroups.append(gr)

    owner, neighbour = [-1] * nrFaces, [-1] * nrIntFaces
    offid, ofvid = 0, 0
    for b in buffers:
        for fi in range(b.fL):
            fnodes, key = b.faces[fi], b.keys[fi]
            if key in facesSorted:
                neighbour[facesSorted[key]] = ofvid
            elif key in bcFacesSorted:
                bcind = bcFacesSorted[key]
                owner[nrIntFaces + bcind] = ofvid
                bcFaces[bcind] = fnodes
            else:
                faces.append(fnodes)
                facesSorted[key] = offid
                owner[offid] = ofvid
                offid += 1
        ofvid += 1

    def write_header(f, ftype):
        f.write("FoamFile\n{\n\tversion 2.0;\n\tformat ascii;\n")
        f.write(f"\tclass {ftype};\n\tlocation \"{base_name}-constant/polyMesh\";\n\tobject {os.path.basename(f.name)};\n}}\n\n")

    with open(os.path.join(dirname, 'points'), 'w') as f:
        write_header(f, "vectorField")
        pts = mesh.GetElementsByType(SMESH.NODE)
        f.write(f"{len(pts)}\n(\n")
        for ni in pts: f.write(f"\t({ ' '.join(map(str, mesh.GetNodeXYZ(ni))) })\n")
        f.write(")\n")

    with open(os.path.join(dirname, 'faces'), 'w') as f:
        write_header(f, "faceList")
        f.write(f"{nrFaces}\n(\n")
        for nodes in faces + bcFaces: f.write(f"\t{len(nodes)}({' '.join(map(str, [p-1 for p in nodes]))})\n")
        f.write(")\n")

    with open(os.path.join(dirname, 'owner'), 'w') as f:
        write_header(f, "labelList")
        f.write(f"{len(owner)}\n(\n" + "\n".join(map(str, owner)) + "\n)\n")

    with open(os.path.join(dirname, 'neighbour'), 'w') as f:
        write_header(f, "labelList")
        f.write(f"{len(neighbour)}\n(\n" + "\n".join(map(str, neighbour)) + "\n)\n")

    with open(os.path.join(dirname, 'boundary'), 'w') as f:
        write_header(f, "polyBoundaryMesh")
        f.write(f"{len(grpNames)}\n(\n")
        for i, name in enumerate(grpNames):
            ptype = "wall" if "surface" in name.lower() else "patch"
            f.write(f"\t{name}\n\t{{\n\t\ttype {ptype};\n\t\tnFaces {grpNrFaces[i]};\n\t\tstartFace {grpStartFace[i]};\n\t}}\n")
        f.write(")\n")

    if volumeGroups:
        s2f = {sa_id: of_id for of_id, sa_id in enumerate(volumes)}
        with open(os.path.join(dirname, 'cellZones'), 'w') as f:
            write_header(f, "regIOobject")
            f.write(f"{len(volumeGroups)}\n(\n")
            for gr in volumeGroups:
                f.write(f"\t{gr.GetName()}\n\t{{\n\t\ttype cellZone;\n\t\tcellLabels List<label>\n")
                ids = gr.GetIDs()
                f.write(f"\t\t{len(ids)}\n\t\t(\n\t\t\t" + "\n\t\t\t".join(map(str, [s2f[i] for i in ids])) + "\n\t\t);\n\t}\n")
            f.write(")\n")

    # == Create 0/ directory (p, U for checkMesh/solver compatibility) ==
    case_parent = os.path.dirname(os.path.dirname(dirname))
    zero_dir = os.path.join(case_parent, "0")
    os.makedirs(zero_dir, exist_ok=True)

    write_patch_field(zero_dir, "p", "volScalarField", grpNames, grpNrFaces, internal_value=0)
    write_patch_field(zero_dir, "U", "volVectorField", grpNames, grpNrFaces, internal_value=0)
    print(f"  > Created 0/p and 0/U (checkMesh compatible)")

    # == Create system/ directory (controlDict, fvSchemes, fvSolution) ==
    sys_dir = os.path.join(case_parent, "system")
    os.makedirs(sys_dir, exist_ok=True)

    # controlDict - minimal for checkMesh
    with open(os.path.join(sys_dir, "controlDict"), 'w') as f:
        f.write("""FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      controlDict;
}

application     checkMesh;

deltaT          1;
writeFrequency  0;

runTimeModifiable true;
""")

    # fvSchemes - default for simpleFoam
    with open(os.path.join(sys_dir, "fvSchemes"), 'w') as f:
        f.write("""FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      fvSchemes;
}

default         none;

divSchemes
{
    default         bounded Gauss upwind;
}

gradSchemes
{
    default         Gauss linear;
}

laplacianSchemes
{
    default         Gauss linear corrected;
}

interpolation
{
    default         linear;
}

snGradSchemes
{
    default         corrected;
}

fluxRequired
{
    default         no;
}
""")

    # fvSolution - SIMPLE for simpleFoam
    with open(os.path.join(sys_dir, "fvSolution"), 'w') as f:
        f.write("""FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      fvSolution;
}

solvers
{
    p
    {
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-07;
        relTol          0;
    }
    U
    {
        solver          PBiCG;
        preconditioner  DILU;
        tolerance       1e-05;
        relTol          0;
    }
}

SIMPLE
{
    nNonOrthogonalCorrecters  0;
}

defaults
{
    log true;
}

relaxationFactors
{
    p           0.3;
    U           0.7;
}
""")

    print(f"  > Created system/controlDict, fvSchemes, fvSolution (checkMesh + solver compatible)")


# ============================ WORKFLOW ============================

def run_compute_mesh():
    # 1. Parse Arguments (JSON file)
    args_file = None
    for arg in sys.argv:
        if arg.endswith('.json'):
            if ':' in arg:
                directory, filename = arg.split(':', 1)
                args_file = os.path.join(directory, filename)
            else:
                args_file = os.path.abspath(arg)
            break

    if not args_file or not os.path.exists(args_file):
        print("ERROR: Args file not found.")
        print("Usage: compute_mesh.py <directory>:<args_file.json>")
        return

    with open(args_file, 'r') as f:
        args = json.load(f)

    step_path = args['step_path']
    base_dir = args['base_dir']
    base_name = args['base_name']
    xl = args['xl']
    yl = args['yl']
    zl = args['zl']
    h1 = args['h1']
    layers = args['layers']
    growth = args['growth']
    fineness = args['fineness']
    T = args['T']
    min_size = args['min_size']
    surf_size = args['surf_size']
    max_size = args['max_size']
    cube_dx = args['cube_dx']
    cube_dy = args['cube_dy']
    cube_dz = args['cube_dz']

    # Refine Box params
    refine_dx = args.get('refine_dx', 0.5 * cube_dx)
    refine_dy = args.get('refine_dy', 2 * yl)
    refine_dz = args.get('refine_dz', 2 * zl)
    refine_cx = args.get('refine_cx', 0)
    refine_cy = args.get('refine_cy', 0)
    refine_cz = args.get('refine_cz', 0)
    refine_tx = args.get('refine_tx', 0)
    refine_ty = args.get('refine_ty', 0)
    refine_tz = args.get('refine_tz', 0)

    # refine_local_size from JSON (Step 4: max_size / 4)
    refine_local_size = args.get('refine_local_size', None)

    # Tip Wake params (optional)
    tip_csv_path = args.get('tip_csv_path', None)
    tip_points_count = args.get('tip_points_count', 0)
    tip_wake_lines = args.get('tip_wake_lines', [])
    tip_wake_refine_size = args.get('tip_wake_refine_size', None)

    setup_hdf = os.path.join(base_dir, f"{base_name}_mesh_setup.hdf")
    mesh_hdf = os.path.join(base_dir, f"{base_name}_mesh.hdf")
    case_dir = os.path.join(base_dir, f"{base_name}-case")

    # 2. Show Parameters
    print("\n" + "="*60)
    print(f"STAGE 2: MESH COMPUTATION (with viscous layers) - {base_name}")
    print("="*60)

    print(f"\n[Mesh Parameters - User Input]")
    user_headers = ["Parameter", "Value", "Description"]
    user_rows = [
        ["h1", f"{h1:.6f} m", "First cell height (BL, for snappyHexMesh)"],
        ["layers", layers, "Boundary layer count (for snappyHexMesh)"],
        ["growth", f"{growth:.4f}", "BL growth rate (for snappyHexMesh)"],
        ["fineness", "Custom", "Custom mesh quality (growth_rate=0.3, segs/edge=1, segs/radius=3)"]
    ]
    print(format_table(user_headers, user_rows))

    # BL thickness calculation (display only)
    T = h1 * (math.pow(growth, layers) - 1) / (growth - 1)

    print(f"\n[Boundary Layer Thickness (calculated, display only)]")
    bl_headers = ["Parameter", "Value", "Formula"]
    bl_rows = [
        ["h1", f"{h1:.6f} m", "First layer height"],
        ["layers", layers, "Number of layers"],
        ["growth", f"{growth:.4f}", "Growth rate"],
        ["T (total)", f"{T:.6f} m", "h1*(growth^layers-1)/(growth-1)"],
    ]
    print(format_table(bl_headers, bl_rows))

    print(f"\n[Mesh Parameters - Derived]")
    derived_headers = ["Parameter", "Value", "Description"]
    derived_rows = [
        ["max_size", f"{max_size:.6f} m", "max(cube_dx, cube_dy, cube_dz) / 50.0 (coarsest cell)"],
        ["surf_size", f"{surf_size:.6f} m", "4 × T (surface cell size)"],
        ["min_size", f"{min_size:.6f} m", "2 × T (BL-based)"],
        ["refine_local_size", f"{refine_local_size:.6f} m", "max_size / 4 (refine box local size)"],
        ["refineBox_dim", f"{refine_dx:.4f} x {refine_dy:.4f} x {refine_dz:.4f}", "RefineBox dimensions (m)"],
        ["refineBox_center", f"({refine_cx:.2f}, {refine_cy:.2f}, {refine_cz:.2f})", "RefineBox center (m)"],
    ]
    if tip_wake_lines:
        derived_rows.append(["tip_wake_lines", len(tip_wake_lines), "Lines from tips to wake"])
        derived_rows.append(["tip_refine_size", f"{tip_wake_refine_size:.6f} m", "Wake line local size (Step 5: surf_size * 2)"])
    print(format_table(derived_headers, derived_rows))

    print(f"\n[Refine Box (wake capture)]")
    print(f"  Size: {refine_dx:.4f} x {refine_dy:.4f} x {refine_dz:.4f} m")
    print(f"  Center: ({refine_cx:.2f}, {refine_cy:.2f}, {refine_cz:.2f})")
    print(f"  Min corner: ({refine_tx:.2f}, {refine_ty:.2f}, {refine_tz:.2f})")
    print(f"  Netgen local size: {refine_local_size:.6f} m (= max_size / 4)")

    # 3. Rebuild Geometry (fresh from STEP)
    print("\n" + "-"*60)
    print("REBUILDING GEOMETRY FROM STEP FILE...")
    print("-"*60)

    imported_shape = geompy.ImportSTEP(step_path)
    geompy.addToStudy(imported_shape, "01_Imported_STEP")

    # Find the smallest face edge length from the STEP file
    # (used to validate min_size before meshing)
    all_shape_faces = geompy.SubShapeAll(imported_shape, geompy.ShapeType["FACE"])
    import math as _math
    smallest_edge = float('inf')
    for face in all_shape_faces:
        edges = geompy.SubShapeAll(face, geompy.ShapeType["EDGE"])
        for edge in edges:
            try:
                e_bb = geompy.BoundingBox(edge)
                e_len = _math.sqrt((e_bb[1]-e_bb[0])**2 + (e_bb[3]-e_bb[2])**2 + (e_bb[5]-e_bb[4])**2)
                if e_len < smallest_edge:
                    smallest_edge = e_len
            except RuntimeError:
                pass  # skip degenerate edge (void bounding box)
    print(f"  Smallest face edge length: {smallest_edge:.8f} m")

    x_min, x_max, y_min, y_max, z_min, z_max = geompy.BoundingBox(imported_shape)
    cx, cy, cz = (x_min + x_max) / 2, (y_min + y_max) / 2, (z_min + z_max) / 2

    try:
        tool_shape = geompy.MakeSolid([imported_shape])
        geompy.addToStudy(tool_shape, "02_Tool_Solid")
    except Exception:
        tool_shape = imported_shape

    cube = geompy.MakeBoxDXDYDZ(cube_dx, cube_dy, cube_dz)
    geompy.addToStudy(cube, "03_Raw_Cube")

    tx, ty, tz = cx - 2.5 * xl, cy - 2.5 * yl, cz - 5.0 * zl
    moved_cube = geompy.MakeTranslation(cube, tx, ty, tz)
    geompy.addToStudy(moved_cube, "04_Farfield_Box")

    c_xmin, c_xmax, c_ymin, c_ymax, c_zmin, c_zmax = geompy.BoundingBox(moved_cube)

    try:
        domain = geompy.MakeCut(moved_cube, tool_shape)
        op_type = "Cut"
    except Exception:
        domain = geompy.MakePartition([moved_cube], [tool_shape])
        op_type = "Partition"

    geompy.addToStudy(domain, f"05_{base_name}_domain")

    # Reduce mesh complexity: use ComputeTolerance to merge close faces
    try:
        domain_clean = geompy.ComputeTolerance(domain, 0.001)
        geompy.addToStudy(domain_clean, f"05_{base_name}_domain_clean")
        domain = domain_clean
        geompy.Display(domain)
    except Exception:
        pass  # Keep original domain if ComputeTolerance fails

    # Adjust min_size if it's larger than the smallest face edge
    # (Netgen cannot mesh edges smaller than min_size)
    if smallest_edge > 0:
        if min_size > smallest_edge:
            old_min_size = min_size
            min_size = smallest_edge
            args['min_size'] = min_size
            print(f"  [min_size] Adjusted: {old_min_size:.6f} m → {min_size:.8f} m")
            print(f"    Reason: smallest face edge ({smallest_edge:.6f} m) < original min_size")
        else:
            print(f"  [min_size] OK: {min_size:.6f} m < smallest face edge ({smallest_edge:.6f} m)")

    # Identify far and model faces
    all_faces = geompy.SubShapeAll(domain, geompy.ShapeType["FACE"])
    tol = 1e-4
    far_faces, model_faces = [], []

    for face in all_faces:
        fb = geompy.BoundingBox(face)
        is_far = any(abs(fb[i] - [c_xmin, c_xmax, c_ymin, c_ymax, c_zmin, c_zmax][i]) < tol for i in range(6))
        if is_far: far_faces.append(face)
        else: model_faces.append(face)

    group_far = geompy.CreateGroup(domain, geompy.ShapeType["FACE"])
    geompy.UnionList(group_far, far_faces)
    geompy.addToStudyInFather(domain, group_far, "far")

    group_model = geompy.CreateGroup(domain, geompy.ShapeType["FACE"])
    geompy.UnionList(group_model, model_faces)
    geompy.addToStudyInFather(domain, group_model, f"{base_name}_surface")

    print(f"  > Boolean Operation: {op_type} Completed")
    print(f"  > Far faces: {len(far_faces)}, Model faces: {len(model_faces)}")

    # 3b. Create Refine Box in SALOME FIRST (before boolean cut, like snappy version)
    #    This ensures local size works on the correct geometry.

    raw_refine_box = geompy.MakeBoxDXDYDZ(refine_dx, refine_dy, refine_dz)
    geompy.addToStudy(raw_refine_box, "RefineBox_Raw")

    refined_refine_box = geompy.MakeTranslation(raw_refine_box, refine_tx, refine_ty, refine_tz)
    geompy.addToStudy(refined_refine_box, "RefineBox")

    rb_xmin, rb_xmax, rb_ymin, rb_ymax, rb_zmin, rb_zmax = geompy.BoundingBox(refined_refine_box)
    rb_cx = (rb_xmin + rb_xmax) / 2
    rb_cy = (rb_ymin + rb_ymax) / 2
    rb_cz = (rb_zmin + rb_zmax) / 2
    print(f"  > RefineBox size: {refine_dx:.4f} x {refine_dy:.4f} x {refine_dz:.4f}")
    print(f"  > RefineBox center: ({rb_cx:.2f}, {rb_cy:.2f}, {rb_cz:.2f})")
    print(f"  > Translate: ({refine_tx:.2f}, {refine_ty:.2f}, {refine_tz:.2f})")

    # Wake Lines from Tip Points (after domain cut, so they intersect the domain boundary)
    wake_line_objects = []
    if tip_wake_lines:
        print(f"\n  Creating {len(tip_wake_lines)} tip wake lines...")
        for i, (x1, y1, z1, x2, y2, z2) in enumerate(tip_wake_lines):
            p1 = geompy.MakeVertex(x1, y1, z1)
            geompy.addToStudy(p1, f"WakeLine_{i}_P1")
            p2 = geompy.MakeVertex(x2, y2, z2)
            geompy.addToStudy(p2, f"WakeLine_{i}_P2")
            wake_line = geompy.MakeEdge(p1, p2)
            geompy.addToStudy(wake_line, f"WakeLine_{i}")
            # Intersect wake line with domain to clip it to domain interior
            try:
                clipped_line = geompy.MakeCut(wake_line, domain)
                geompy.addToStudy(clipped_line, f"WakeLine_{i}_clipped")
                geompy.Display(clipped_line)
                wake_line = clipped_line
            except Exception:
                pass
            wake_line_objects.append(wake_line)
            print(f"    Line {i+1}: ({x1:.4f}, {y1:.4f}, {z1:.4f}) -> ({x2:.4f}, {y2:.4f}, {z2:.4f})")
        print(f"  > Created {len(wake_line_objects)} wake lines")
    else:
        print(f"\n  No tip wake lines (tip CSV not found)")

    # --- Refine Box volume group for Netgen local size ---
    refine_box_volume_group = geompy.CreateGroup(refined_refine_box, geompy.ShapeType["SOLID"])
    refine_box_solids = geompy.SubShapeAll(refined_refine_box, geompy.ShapeType["SOLID"])
    if refine_box_solids:
        geompy.UnionList(refine_box_volume_group, refine_box_solids)
    geompy.addToStudyInFather(refined_refine_box, refine_box_volume_group, "refineBox_volume")
    print(f"  > RefineBox volume group: 'refineBox_volume'")
    print(f"  > Netgen local size for refineBox: {refine_local_size:.6f} m (= max_size / 4)")

    # 4. Mesh Setup & Computation (with viscous layers)
    print("\n" + "="*60)
    print("STAGE 3: MESH SETUP & COMPUTATION (with viscous layers)")
    print("="*60)

    print("\n  Setting up mesh parameters...")
    mesh = smesh.Mesh(domain, f"{base_name}_mesh")
    netgen = mesh.Tetrahedron(algo=smeshBuilder.NETGEN_1D2D3D)

    params = netgen.Parameters()
    params.SetNbThreads(8)
    params.SetMaxSize(max_size)
    params.SetMinSize(min_size)
    params.SetLocalSizeOnShape(group_model, surf_size)
    params.SetUseSurfaceCurvature(1)
    # params.SetFineness(fineness)  # Use custom params (growth_rate=0.3, segs/edge=1, segs/radius=3)

    # Custom mesh quality params (commented out - use custom params directly):
    # params.SetFineness(fineness)  # deleted - use custom params directly
    params.SetGrowthRate(0.3)
    params.SetNbSegPerEdge(1)
    params.SetNbSegPerRadius(3)
    # Custom mesh quality params (disabled):
    # params.SetNbSurfOptSteps(3)        # Surface mesh optimization → skewness ↓
    # params.SetNbVolOptSteps(0)         # Volume optimization
    params.SetOptimize(1)              # 3D tet optimization (ENABLED)
    # params.SetSecondOrder(0)           # Linear elements (OpenFOAM compat)

    print("  > Mesh quality: Custom (growth_rate=0.3, segs/edge=1, segs/radius=3) + SetOptimize(1)")
    netgen.SetLocalSizeOnShape(refine_box_volume_group, refine_local_size)

    print("  Defining mesh groups...")
    mesh.GroupOnGeom(group_far, 'far', SMESH.FACE)
    mesh.GroupOnGeom(group_model, f'{base_name}_surface', SMESH.FACE)

    print(f"  Configuring viscous layers: {layers} layers, growth {growth}, firstLayerHeight {h1:.6f} m")
    netgen.ViscousLayers(h1, layers, growth, far_faces, 1, smeshBuilder.FACE_OFFSET)

    if wake_line_objects:
        print(f"  Applying Netgen local size to {len(wake_line_objects)} wake lines: {tip_wake_refine_size:.6f} m (Step 5: surf_size * 2)")
        for wake_line in wake_line_objects:
            netgen.SetLocalSizeOnShape(wake_line, tip_wake_refine_size)
        print(f"  > Wake line local size applied successfully")

    salome.myStudy.SaveAs(setup_hdf, False, False)
    print(f"  > Mesh Setup Saved: {os.path.basename(setup_hdf)}")

    print("  > Mesh quality: Custom (growth_rate=0.3, segs/edge=1, segs/radius=3) + SetOptimize(1)")
    print("\n  Computing mesh...")
    sys.stdout.flush()
    sys.stderr.flush()

    start_time = time.time()

    success = mesh.Compute()
    duration = time.time() - start_time

    if not success and success is not None:
        print(f"\n  mesh.Compute() returned False")
        print(f"  NbVolumes: {mesh.NbVolumes()}, NbFaces: {mesh.NbFaces()}, NbEdges: {mesh.NbEdges()}")
        for gr in mesh.GetGroups():
            print(f"  Group: {gr.GetName()} type={gr.GetType()} nElements={gr.GetNumberOfElements()}")

    if success:
        duration = time.time() - start_time
        print(f"\n\n[Computation Statistics]")
        print(f"  Time Taken: {duration:.2f} seconds")
        print(f"  Volumes:    {mesh.NbVolumes()}")
        print(f"  Faces:      {mesh.NbFaces()}")
        print(f"  Edges:      {mesh.NbEdges()}")

        salome.myStudy.SaveAs(mesh_hdf, False, False)
        print(f"\n  > Mesh Saved: {os.path.basename(mesh_hdf)}")

        # Export to OpenFOAM case (complete structure)
        os.makedirs(os.path.join(case_dir, "constant", "polyMesh"), exist_ok=True)
        foam_out = os.path.join(case_dir, "constant", "polyMesh")
        print(f"\n  > Exporting to OpenFOAM case polyMesh...")
        try:
            exportToFoam(mesh, foam_out, base_name)
            print(f"  > Export Complete: {foam_out}")

            # Verify export
            exported_files = os.listdir(foam_out)
            print(f"  > Exported files: {', '.join(exported_files)}")

            # Create case.foam marker file
            case_foam_path = os.path.join(case_dir, "case.foam")
            with open(case_foam_path, 'w') as f:
                f.write("# OpenFOAM case marker\n")
                f.write("# Created by compute_mesh.py\n")
                f.write(f"# {base_name}\n")
            print(f"  > Created case.foam marker: {case_foam_path}")

            # Show case structure
            print(f"\n  > Complete case structure:")
            print(f"    {case_dir}/")
            print(f"    ├── 0/")
            print(f"    │   ├── p")
            print(f"    │   └── U")
            print(f"    ├── case.foam")
            print(f"    ├── constant/")
            print(f"    │   └── polyMesh/")
            print(f"    │       ├── boundary")
            print(f"    │       ├── cellZones")
            print(f"    │       ├── faces")
            print(f"    │       ├── neighbour")
            print(f"    │       ├── owner")
            print(f"    │       └── points")
            print(f"    └── system/")
            print(f"        ├── controlDict   (application=checkMesh)")
            print(f"        ├── fvSchemes     (default schemes)")
            print(f"        └── fvSolution    (SIMPLE solver)")
            print(f"\n  checkMesh: cd {case_dir} && checkMesh")
            print(f"  simpleFoam: cd {case_dir} && simpleFoam")

            # ---- Auto-run checkMesh ----
            print(f"\n  Running checkMesh...")
            checklog_path = os.path.join(case_dir, "checkMesh.log")
            check_cmd = f"bash -c 'source /opt/OpenFOAM/OpenFOAM-v2512/etc/bashrc 2>/dev/null && cd {case_dir} && checkMesh 2>&1 | tee {checklog_path}'"
            ret = os.system(check_cmd)
            if ret == 0:
                print(f"  > checkMesh completed (log: {checklog_path})")
            else:
                print(f"  > checkMesh exited with code {ret}")

            # ---- Print checkMesh results ----
            print("\n" + "="*60)
            print("CHECKMESH RESULTS")
            print("="*60)
            with open(checklog_path, 'r') as f:
                content = f.read()
            for line in content.split('\n'):
                if ('Number of cells' in line or 'Number of links' in line or
                    'Number of faces' in line or 'Number of bytes' in line or
                    'quality' in line or 'max' in line or 'min' in line or
                    'Inside the domain' in line or 'Outside the domain' in line or
                    'boundary quality' in line or 'Summation' in line or
                    'General cell quality' in line or 'General face quality' in line or
                    'max cell volume' in line or 'max edge length' in line or
                    'max face thickness' in line or 'max face skewness' in line or
                    'max non-orthogonality' in line or 'max skewness' in line or
                    'max rotation angle' in line or 'max pyramid volume' in line or
                    'max relative volume' in line or 'max contact ratio' in line or
                    'Number of illegal faces' in line or 'Illegal face' in line or
                    'Found' in line or 'Detected' in line or 'wrote' in line or
                    'The mesh' in line or 'cell volumes' in line):
                    print(f"  {line}")

        except Exception as e:
            import traceback
            print(f"  > exportToFoam ERROR: {e}")
            traceback.print_exc()

        print("\n" + "="*60)
        print("WORKFLOW COMPLETE")
        print("="*60)
        print(f"\n  OpenFOAM case ready at: {case_dir}")
        print("="*60)

    else:
        print("\n  > ERROR: Mesh computation failed.")

if __name__ == "__main__":
    run_compute_mesh()
